version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pdf_signing_postgres
    environment:
      POSTGRES_USER: pdf_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: pdf_signing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
